### Cadastrar uma nova forma de pagamento
POST https://localhost:5001/api/pagamento/create
Content-Type: application/json

{
    "Nome" : "Crédito",
    "Vezes" : 4
}

### Listar todas as formas de pagamento
GET https://localhost:5001/api/pagamento/list