### Criar venda
POST https://localhost:5001/api/venda/create
Content-Type: application/json

{
    "Cliente": "Liandra Mary",
    "PagamentoId": 1
}

### Listar vendas
GET  https://localhost:5001/api/venda/list